// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfunytkuwyletyshrhkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdW55dGt1d3lsZXR5c2hyaGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MTI5ODEsImV4cCI6MjA5NDE4ODk4MX0.WrB7aUZOo5UDutTA9TG705ESQ_7xmgTmgE7RybzmaTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});